#!/bin/bash
## named 서비스 설치
install_named(){
    # bind, bind-chroot, bind-utils 설치
    echo "DNS 구축을 위한 패키지를 설치합니다. (bind, bind-chroot, bind-utils)"
    yum install -y bind bind-chroot bind-utils &>> $LOG_FILE

    # resolv.conf 서버 ip로 수정
    echo "resolv.conf 초기화합니다."
    cat << EOF > /etc/resolv.conf
# Generated by NetworkManager
nameserver ${DNS_IP}
nameserver 8.8.8.8
EOF

    # named.conf 초기화 (/etc/named.conf)
    # 공백 무관하게 치환하기 위해서 \s* 사용 -> 어차피 새로 설치 했기 때문에 공백 상관 없음 (allow query만 적용)
    echo "named.conf 설정 파일을 수정합니다."
    sed -i 's/listen-on port 53 { 127.0.0.1; };/listen-on port 53 { any; };/' /etc/named.conf &>> $LOG_FILE
    sed -i 's/listen-on-v6 port 53 { ::1; };/listen-on-v6 port 53 { none; };/' /etc/named.conf &>> $LOG_FILE
    sed -i 's/allow-query\s*{\s*localhost;\s*};/allow-query { any; };/' /etc/named.conf &>> $LOG_FILE
    
    # 방화벽을 on / off 체크하고 포트를 추가
    echo "방화벽에 53번 포트가 열려 있는지 확인합니다."
    if firewall-cmd --state &>> $LOG_FILE; then
        echo "방화벽이 켜져 있습니다. 53번 포트를 확인합니다."
        # 방화벽 포트 추가 (53/tcp, 53/udp)
        if ! firewall-cmd --query-port=53/tcp &>> $LOG_FILE || ! firewall-cmd --query-port=53/udp &>> $LOG_FILE; then
            echo "53번 포트가 열려 있지 않습니다. 53번 포트를 추가합니다."
            firewall-cmd --add-port=53/tcp --permanent &>> $LOG_FILE
            firewall-cmd --add-port=53/udp --permanent &>> $LOG_FILE
            firewall-cmd --reload &>> $LOG_FILE
        fi
    else
        echo "방화벽이 꺼져 있습니다."
    fi

    # SELinux 체크 및 named 예외 처리
    echo "시스템 방화벽 SELinux 상태를 확인합니다."
    if [ "$(getenforce)" = "Enforcing" ]; then
        echo "SELinux가 켜져 있습니다. dns 서비스를 예외 처리합니다."
        semanage permissive -a named_t &>> $LOG_FILE    
    else
        echo "SELinux가 Enforcing 상태가 아닙니다."
    fi

    echo "DNS가 설치되었습니다."
}

## named 서비스 삭제
delete_named(){
    local logfile=$LOG_FILE
    local isdelete  # DNS 서비스 삭제 여부
    local isdeleterelated   # 관련 파일 삭제 여부
    while :
    do
        read -p "DNS 서비스를 삭제하시겠습니까? (y/n) : " isdelete
        case $isdelete in
            y) 
                echo "DNS 서비스 삭제를 진행합니다."
                break 
                ;;
            n) 
                echo "DNS 서비스 삭제를 취소합니다."
                return 1 
                ;;
            *) 
                echo "잘못된 입력입니다. 다시 시도해주세요." 
                ;;
        esac
    done
    while :
    do
        echo "서비스 관련 디렉토리, 설정 파일, zone 파일을 삭제하시겠습니까? (y/n)"
        echo "삭제 대상 : /etc/named*, /var/named/, /var/named/chroot/"
        read isdeleterelated
        case $isdeleterelated in
            y)
                # 백업 진행
                echo "서비스 관련 디렉토리, 설정 파일, zone 파일을 삭제하기 전에 백업을 진행합니다."
                local backuppath="$SCRIPT_DIR/dns_backup_$(date +%Y%m%d)"
                mkdir -p "$backuppath" &>> $LOG_FILE
                echo "백업 위치: $backuppath"
                cp -a /etc/named* "$backuppath/" &>> $LOG_FILE
                cp -a /var/named/ "$backuppath/named" &>> $LOG_FILE
                
                echo "서비스 관련 디렉토리, 설정 파일, zone 파일을 삭제합니다."
                rm -rf /etc/named* &>> $LOG_FILE  # /etc 폴더 안의 모든 설정 파일 제거
                rm -rf /var/named/ &>> $LOG_FILE  # Zone 파일 제거
                break 
                ;;
            n) 
                echo "서비스 관련 디렉토리, 설정 파일, zone 파일을 남겨둡니다."
                break
                ;;
            *) 
                echo "잘못된 입력입니다. 다시 시도해주세요." 
                ;;
        esac
    done
    
    # resolv.conf 초기화
    echo "resolv.conf 초기화합니다."
    > /etc/resolv.conf

    cat << EOF > /etc/resolv.conf
# Generated by NetworkManager
nameserver 8.8.8.8
nameserver 1.1.1.1
EOF

    # 방화벽을 on / off 체크하고 포트를 해제
    echo "방화벽에 53번 포트가 열려 있는지 확인합니다."
    if firewall-cmd --state &>> $LOG_FILE; then
        echo "방화벽이 켜져 있습니다. 53번 포트를 확인합니다."
        if firewall-cmd --query-port=53/tcp &>> $LOG_FILE || firewall-cmd --query-port=53/udp &>> $LOG_FILE; then
            echo "53번 포트가 열려 있습니다. 53번 포트를 해제합니다."
            firewall-cmd --remove-port=53/tcp --permanent &>> $LOG_FILE
            firewall-cmd --remove-port=53/udp --permanent &>> $LOG_FILE
            firewall-cmd --reload &>> $LOG_FILE
        fi
        echo "53번 포트가 해제되었습니다."
    else
        echo "방화벽이 꺼져 있습니다."
    fi

    yum remove bind -y &>> $LOG_FILE
    echo "DNS가 제거되었습니다."
}