#!/bin/bash
# ============================================================
# 도커 환경용 dns_crud.sh
# 주요 변경사항:
#   - systemctl → named 프로세스 직접 관리 (kill / named -c)
#   - yum/rpm → dnf (Rocky Linux 9 기준)
#   - firewall-cmd → 제거 (도커 네트워크로 포트 노출)
#   - SELinux 처리 → 제거 (컨테이너 내부에서 비활성)
#   - hostname -I → ip route 로 IP 취득
# ============================================================

## named 서비스 설치 (도커: 패키지는 이미 이미지에 포함, 설정만 초기화)
install_named(){
    echo "DNS 구축을 위한 설정을 초기화합니다."

    # resolv.conf 서버 ip로 수정
    echo "resolv.conf 초기화합니다."
    cat << EOF > /etc/resolv.conf
# Generated by dns-manager
nameserver ${DNS_IP}
nameserver 8.8.8.8
EOF

    # named.conf 초기화
    echo "named.conf 설정 파일을 수정합니다."
    sed -i 's/listen-on port 53 { 127.0.0.1; };/listen-on port 53 { any; };/' /etc/named.conf &>> "$LOG_FILE"
    sed -i 's/listen-on-v6 port 53 { ::1; };/listen-on-v6 port 53 { none; };/' /etc/named.conf &>> "$LOG_FILE"
    sed -i 's/allow-query\s*{\s*localhost;\s*};/allow-query { any; };/' /etc/named.conf &>> "$LOG_FILE"

    # DNS 데이터 파일 초기화
    echo "DNS 서버에 대한 데이터를 초기화합니다."
    cat << EOF > "${SCRIPT_DIR}/data/dns_data.txt"
MASTER_IP:${DNS_IP}
SLAVE_IP:
TYPE:none
ZONE_DECL_SERIAL:$(date +%Y%m%d)01
ZONE_DECL_PATH:/etc/named.rfc1912.zones
EOF

    # named 실행 (foreground → background로 기동)
    named -c /etc/named.conf &>> "$LOG_FILE" &
    echo "DNS가 시작되었습니다. (PID: $!)"
}

## named 실행 여부 확인 (systemctl 대신 프로세스 체크)
is_named_running() {
    if pgrep -x named > /dev/null 2>&1; then
        echo "true"
    else
        echo "false"
    fi
}

## dns_data.txt에서 타입 반환
get_dns_type() {
    echo $(awk -F':' '/TYPE/ {print $2}' "${SCRIPT_DIR}/data/dns_data.txt")
}

## named 서비스 삭제 (도커: 패키지 제거 없이 프로세스 종료 + 설정 초기화)
delete_named(){
    local _isdelete
    while :
    do
        read -p "DNS 서비스를 삭제하시겠습니까? 설정 파일, zone 파일을 모두 삭제합니다. (y/n) : " _isdelete
        case $_isdelete in
            y) echo "DNS 서비스 삭제를 진행합니다."; break ;;
            n) echo "DNS 서비스 삭제를 취소합니다."; return 1 ;;
            *) echo "잘못된 입력입니다. 다시 시도해주세요." ;;
        esac
    done

    # 백업
    local _backuppath="$SCRIPT_DIR/data/dns_backup_$(date +%Y%m%d)"
    mkdir -p "$_backuppath" &>> "$LOG_FILE"
    echo "백업 위치: $_backuppath"
    cp -a /etc/named* "$_backuppath/" &>> "$LOG_FILE"
    cp -a /var/named/ "$_backuppath/named" &>> "$LOG_FILE"

    # named 프로세스 종료
    if pgrep -x named > /dev/null 2>&1; then
        kill $(pgrep -x named)
        echo "named 프로세스를 종료했습니다."
    fi

    # 설정 파일 삭제
    rm -rf /etc/named* &>> "$LOG_FILE"
    rm -rf /var/named/ &>> "$LOG_FILE"

    # resolv.conf 초기화
    cat << EOF > /etc/resolv.conf
# Generated by dns-manager
nameserver 8.8.8.8
nameserver 1.1.1.1
EOF

    # dns_data.txt 초기화
    rm -f "${SCRIPT_DIR}/data/dns_data.txt"

    echo "DNS가 제거되었습니다."
}
